echo "---build start---"

stage('Checkout Stage') {
		echo "---Checkout---"
		echo "${P_VERSION}"
}

stage('Build Stage') {
		echo "---Build Stage---"
		sh 'docker container ls'
}

stage('Push Stage') {
		echo "---Push Stage---"
}
